// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonsterHunterMini.Database;

#nullable disable

namespace MonsterHunterMini.Migrations
{
    [DbContext(typeof(MonsterHunterMiniDb))]
    [Migration("20260309214959_SeedInitialMaterials")]
    partial class SeedInitialMaterials
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MonsterHunterMini.Armor", b =>
                {
                    b.Property<int>("WeaponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WeaponId"));

                    b.Property<double>("Defense")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WeaponId");

                    b.ToTable("Armor");
                });

            modelBuilder.Entity("MonsterHunterMini.Material", b =>
                {
                    b.Property<int>("MaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaterialId"));

                    b.Property<int?>("ArmorWeaponId")
                        .HasColumnType("int");

                    b.Property<int?>("MonsterId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int?>("WeaponId")
                        .HasColumnType("int");

                    b.HasKey("MaterialId");

                    b.HasIndex("ArmorWeaponId");

                    b.HasIndex("MonsterId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("WeaponId");

                    b.ToTable("Material");

                    b.HasData(
                        new
                        {
                            MaterialId = 1,
                            Name = "Rathalos Scale"
                        },
                        new
                        {
                            MaterialId = 2,
                            Name = "Rathalos Tail"
                        },
                        new
                        {
                            MaterialId = 3,
                            Name = "Rathalos Webbing"
                        },
                        new
                        {
                            MaterialId = 4,
                            Name = "Rathian Scale"
                        },
                        new
                        {
                            MaterialId = 5,
                            Name = "Rathian Tail"
                        },
                        new
                        {
                            MaterialId = 6,
                            Name = "Rathian Webbing"
                        },
                        new
                        {
                            MaterialId = 7,
                            Name = "Diablos Ridge"
                        },
                        new
                        {
                            MaterialId = 8,
                            Name = "Diablos Tailcase"
                        },
                        new
                        {
                            MaterialId = 9,
                            Name = "Twisted Horn"
                        });
                });

            modelBuilder.Entity("MonsterHunterMini.Monster", b =>
                {
                    b.Property<int>("MonsterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MonsterId"));

                    b.Property<int>("Attack")
                        .HasColumnType("int");

                    b.Property<int>("Defense")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MonsterId");

                    b.ToTable("Monsters");

                    b.HasData(
                        new
                        {
                            MonsterId = 1,
                            Attack = 7,
                            Defense = 7,
                            Name = "Rathalos"
                        },
                        new
                        {
                            MonsterId = 2,
                            Attack = 9,
                            Defense = 7,
                            Name = "Rathian"
                        },
                        new
                        {
                            MonsterId = 3,
                            Attack = 6,
                            Defense = 7,
                            Name = "Diablos"
                        },
                        new
                        {
                            MonsterId = 4,
                            Attack = 3,
                            Defense = 3,
                            Name = "Velocidrome"
                        },
                        new
                        {
                            MonsterId = 5,
                            Attack = 4,
                            Defense = 4,
                            Name = "Yian-Kut-Ku"
                        },
                        new
                        {
                            MonsterId = 6,
                            Attack = 4,
                            Defense = 3,
                            Name = "Iodrome"
                        });
                });

            modelBuilder.Entity("MonsterHunterMini.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerId"));

                    b.Property<int>("EquippedArmorWeaponId")
                        .HasColumnType("int");

                    b.Property<int>("EquippedWeaponWeaponId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PlayerId");

                    b.HasIndex("EquippedArmorWeaponId");

                    b.HasIndex("EquippedWeaponWeaponId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("MonsterHunterMini.Weapon", b =>
                {
                    b.Property<int>("WeaponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WeaponId"));

                    b.Property<double>("Attack")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WeaponId");

                    b.ToTable("Weapon");
                });

            modelBuilder.Entity("MonsterHunterMini.Material", b =>
                {
                    b.HasOne("MonsterHunterMini.Armor", null)
                        .WithMany("Materials")
                        .HasForeignKey("ArmorWeaponId");

                    b.HasOne("MonsterHunterMini.Monster", null)
                        .WithMany("Drops")
                        .HasForeignKey("MonsterId");

                    b.HasOne("MonsterHunterMini.Player", null)
                        .WithMany("Inventory")
                        .HasForeignKey("PlayerId");

                    b.HasOne("MonsterHunterMini.Weapon", null)
                        .WithMany("Materials")
                        .HasForeignKey("WeaponId");
                });

            modelBuilder.Entity("MonsterHunterMini.Player", b =>
                {
                    b.HasOne("MonsterHunterMini.Armor", "EquippedArmor")
                        .WithMany()
                        .HasForeignKey("EquippedArmorWeaponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonsterHunterMini.Weapon", "EquippedWeapon")
                        .WithMany()
                        .HasForeignKey("EquippedWeaponWeaponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EquippedArmor");

                    b.Navigation("EquippedWeapon");
                });

            modelBuilder.Entity("MonsterHunterMini.Armor", b =>
                {
                    b.Navigation("Materials");
                });

            modelBuilder.Entity("MonsterHunterMini.Monster", b =>
                {
                    b.Navigation("Drops");
                });

            modelBuilder.Entity("MonsterHunterMini.Player", b =>
                {
                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("MonsterHunterMini.Weapon", b =>
                {
                    b.Navigation("Materials");
                });
#pragma warning restore 612, 618
        }
    }
}
