// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonsterHunterMini.Database;

#nullable disable

namespace MonsterHunterMini.Migrations
{
    [DbContext(typeof(MonsterHunterMiniDb))]
    [Migration("20260311215015_EquipmentSeed")]
    partial class EquipmentSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MonsterHunterMini.Armor", b =>
                {
                    b.Property<int>("ArmorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArmorId"));

                    b.Property<double>("Defense")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ArmorId");

                    b.ToTable("Armor");

                    b.HasData(
                        new
                        {
                            ArmorId = 1,
                            Defense = 12.0,
                            Name = "Rathalos Set"
                        },
                        new
                        {
                            ArmorId = 2,
                            Defense = 10.0,
                            Name = "Rathian Set"
                        },
                        new
                        {
                            ArmorId = 3,
                            Defense = 15.0,
                            Name = "Diablos Set"
                        });
                });

            modelBuilder.Entity("MonsterHunterMini.Classes.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerId"));

                    b.Property<int>("EquippedArmorArmorId")
                        .HasColumnType("int");

                    b.Property<int>("EquippedWeaponWeaponId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PlayerId");

                    b.HasIndex("EquippedArmorArmorId");

                    b.HasIndex("EquippedWeaponWeaponId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("MonsterHunterMini.Material", b =>
                {
                    b.Property<int>("MaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaterialId"));

                    b.Property<int?>("ArmorId")
                        .HasColumnType("int");

                    b.Property<decimal>("DropRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MonsterId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int?>("WeaponId")
                        .HasColumnType("int");

                    b.HasKey("MaterialId");

                    b.HasIndex("ArmorId");

                    b.HasIndex("MonsterId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("WeaponId");

                    b.ToTable("Material");

                    b.HasData(
                        new
                        {
                            MaterialId = 1,
                            DropRate = 0.6m,
                            MonsterId = 1,
                            Name = "Rathalos Scale"
                        },
                        new
                        {
                            MaterialId = 2,
                            DropRate = 0.5m,
                            MonsterId = 1,
                            Name = "Rathalos Tail"
                        },
                        new
                        {
                            MaterialId = 3,
                            DropRate = 0.4m,
                            MonsterId = 1,
                            Name = "Rathalos Webbing"
                        },
                        new
                        {
                            MaterialId = 4,
                            DropRate = 0.6m,
                            MonsterId = 2,
                            Name = "Rathian Scale"
                        },
                        new
                        {
                            MaterialId = 5,
                            DropRate = 0.5m,
                            MonsterId = 2,
                            Name = "Rathian Tail"
                        },
                        new
                        {
                            MaterialId = 6,
                            DropRate = 0.4m,
                            MonsterId = 2,
                            Name = "Rathian Webbing"
                        },
                        new
                        {
                            MaterialId = 7,
                            DropRate = 0.6m,
                            MonsterId = 3,
                            Name = "Diablos Ridge"
                        },
                        new
                        {
                            MaterialId = 8,
                            DropRate = 0.4m,
                            MonsterId = 3,
                            Name = "Diablos Tailcase"
                        },
                        new
                        {
                            MaterialId = 9,
                            DropRate = 0.25m,
                            MonsterId = 3,
                            Name = "Twisted Horn"
                        });
                });

            modelBuilder.Entity("MonsterHunterMini.Monster", b =>
                {
                    b.Property<int>("MonsterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MonsterId"));

                    b.Property<int>("Attack")
                        .HasColumnType("int");

                    b.Property<int>("Defense")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MonsterId");

                    b.ToTable("Monsters");

                    b.HasData(
                        new
                        {
                            MonsterId = 1,
                            Attack = 7,
                            Defense = 7,
                            Name = "Rathalos"
                        },
                        new
                        {
                            MonsterId = 2,
                            Attack = 9,
                            Defense = 7,
                            Name = "Rathian"
                        },
                        new
                        {
                            MonsterId = 3,
                            Attack = 6,
                            Defense = 7,
                            Name = "Diablos"
                        },
                        new
                        {
                            MonsterId = 4,
                            Attack = 3,
                            Defense = 3,
                            Name = "Velocidrome"
                        },
                        new
                        {
                            MonsterId = 5,
                            Attack = 4,
                            Defense = 4,
                            Name = "Yian-Kut-Ku"
                        },
                        new
                        {
                            MonsterId = 6,
                            Attack = 4,
                            Defense = 3,
                            Name = "Iodrome"
                        });
                });

            modelBuilder.Entity("MonsterHunterMini.Weapon", b =>
                {
                    b.Property<int>("WeaponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WeaponId"));

                    b.Property<double>("Attack")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WeaponId");

                    b.ToTable("Weapon");

                    b.HasData(
                        new
                        {
                            WeaponId = 1,
                            Attack = 10.0,
                            Name = "Rathalos Greatsword"
                        },
                        new
                        {
                            WeaponId = 2,
                            Attack = 9.0,
                            Name = "Rathian Greatsword"
                        },
                        new
                        {
                            WeaponId = 3,
                            Attack = 12.0,
                            Name = "Diablos Greatsword"
                        });
                });

            modelBuilder.Entity("MonsterHunterMini.Classes.Player", b =>
                {
                    b.HasOne("MonsterHunterMini.Armor", "EquippedArmor")
                        .WithMany()
                        .HasForeignKey("EquippedArmorArmorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonsterHunterMini.Weapon", "EquippedWeapon")
                        .WithMany()
                        .HasForeignKey("EquippedWeaponWeaponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EquippedArmor");

                    b.Navigation("EquippedWeapon");
                });

            modelBuilder.Entity("MonsterHunterMini.Material", b =>
                {
                    b.HasOne("MonsterHunterMini.Armor", null)
                        .WithMany("Materials")
                        .HasForeignKey("ArmorId");

                    b.HasOne("MonsterHunterMini.Monster", "Monster")
                        .WithMany("Drops")
                        .HasForeignKey("MonsterId");

                    b.HasOne("MonsterHunterMini.Classes.Player", "Player")
                        .WithMany("Inventory")
                        .HasForeignKey("PlayerId");

                    b.HasOne("MonsterHunterMini.Weapon", null)
                        .WithMany("Materials")
                        .HasForeignKey("WeaponId");

                    b.Navigation("Monster");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("MonsterHunterMini.Armor", b =>
                {
                    b.Navigation("Materials");
                });

            modelBuilder.Entity("MonsterHunterMini.Classes.Player", b =>
                {
                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("MonsterHunterMini.Monster", b =>
                {
                    b.Navigation("Drops");
                });

            modelBuilder.Entity("MonsterHunterMini.Weapon", b =>
                {
                    b.Navigation("Materials");
                });
#pragma warning restore 612, 618
        }
    }
}
