// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonsterHunterMini.Database;

#nullable disable

namespace MonsterHunterMini.Migrations
{
    [DbContext(typeof(MonsterHunterMiniDb))]
    [Migration("20260306045845_AddedPlayer")]
    partial class AddedPlayer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MonsterHunterMini.Armor", b =>
                {
                    b.Property<int>("WeaponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WeaponId"));

                    b.Property<double>("Defense")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WeaponId");

                    b.ToTable("Armor");
                });

            modelBuilder.Entity("MonsterHunterMini.Material", b =>
                {
                    b.Property<int>("MaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaterialId"));

                    b.Property<int?>("ArmorWeaponId")
                        .HasColumnType("int");

                    b.Property<int?>("MonsterId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int?>("WeaponId")
                        .HasColumnType("int");

                    b.HasKey("MaterialId");

                    b.HasIndex("ArmorWeaponId");

                    b.HasIndex("MonsterId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("WeaponId");

                    b.ToTable("Material");
                });

            modelBuilder.Entity("MonsterHunterMini.Monster", b =>
                {
                    b.Property<int>("MonsterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MonsterId"));

                    b.Property<int>("Attack")
                        .HasColumnType("int");

                    b.Property<int>("Defense")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MonsterId");

                    b.ToTable("Monsters");
                });

            modelBuilder.Entity("MonsterHunterMini.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerId"));

                    b.Property<int>("EquippedArmorWeaponId")
                        .HasColumnType("int");

                    b.Property<int>("EquippedWeaponWeaponId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlayerId");

                    b.HasIndex("EquippedArmorWeaponId");

                    b.HasIndex("EquippedWeaponWeaponId");

                    b.ToTable("PLayers");
                });

            modelBuilder.Entity("MonsterHunterMini.Weapon", b =>
                {
                    b.Property<int>("WeaponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WeaponId"));

                    b.Property<double>("Attack")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WeaponId");

                    b.ToTable("Weapon");
                });

            modelBuilder.Entity("MonsterHunterMini.Material", b =>
                {
                    b.HasOne("MonsterHunterMini.Armor", null)
                        .WithMany("Materials")
                        .HasForeignKey("ArmorWeaponId");

                    b.HasOne("MonsterHunterMini.Monster", null)
                        .WithMany("Drops")
                        .HasForeignKey("MonsterId");

                    b.HasOne("MonsterHunterMini.Player", null)
                        .WithMany("Inventory")
                        .HasForeignKey("PlayerId");

                    b.HasOne("MonsterHunterMini.Weapon", null)
                        .WithMany("Materials")
                        .HasForeignKey("WeaponId");
                });

            modelBuilder.Entity("MonsterHunterMini.Player", b =>
                {
                    b.HasOne("MonsterHunterMini.Armor", "EquippedArmor")
                        .WithMany()
                        .HasForeignKey("EquippedArmorWeaponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonsterHunterMini.Weapon", "EquippedWeapon")
                        .WithMany()
                        .HasForeignKey("EquippedWeaponWeaponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EquippedArmor");

                    b.Navigation("EquippedWeapon");
                });

            modelBuilder.Entity("MonsterHunterMini.Armor", b =>
                {
                    b.Navigation("Materials");
                });

            modelBuilder.Entity("MonsterHunterMini.Monster", b =>
                {
                    b.Navigation("Drops");
                });

            modelBuilder.Entity("MonsterHunterMini.Player", b =>
                {
                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("MonsterHunterMini.Weapon", b =>
                {
                    b.Navigation("Materials");
                });
#pragma warning restore 612, 618
        }
    }
}
